--
-- PostgreSQL database dump
--

\restrict eDQTXbxkuUIEgGuqwWZD69CCsy5O8eyo9FK3gWvNTmdTLFcHgaAUlnDr0XdRdD1

-- Dumped from database version 17.8 (130b160)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO neondb_owner;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO neondb_owner;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO neondb_owner;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO neondb_owner;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO neondb_owner;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO neondb_owner;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_accion; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_accion (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    es_sistema boolean NOT NULL,
    genera_detalle boolean NOT NULL,
    detalle_tipo character varying(10) NOT NULL,
    detalle_descripcion character varying(40) NOT NULL,
    detalle_notas text NOT NULL,
    enviar_email boolean NOT NULL,
    email_to character varying(254) NOT NULL,
    email_cc text NOT NULL,
    email_bcc text NOT NULL,
    email_subject character varying(254) NOT NULL,
    email_body text NOT NULL,
    email_attachments boolean NOT NULL,
    email_editable boolean NOT NULL
);


ALTER TABLE public.core_accion OWNER TO neondb_owner;

--
-- Name: core_accion_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_accion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_accion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_calidad; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_calidad (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    notas text NOT NULL
);


ALTER TABLE public.core_calidad OWNER TO neondb_owner;

--
-- Name: core_calidad_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_calidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_calidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_categoria; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_categoria (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    notas text NOT NULL
);


ALTER TABLE public.core_categoria OWNER TO neondb_owner;

--
-- Name: core_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cliente; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_cliente (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    representante_id bigint NOT NULL
);


ALTER TABLE public.core_cliente OWNER TO neondb_owner;

--
-- Name: core_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_comercial; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_comercial (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(40) NOT NULL
);


ALTER TABLE public.core_comercial OWNER TO neondb_owner;

--
-- Name: core_comercial_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_comercial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_comercial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_configuracion; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_configuracion (
    id bigint NOT NULL,
    nombre_empresa character varying(40) NOT NULL,
    dir_general_email character varying(254) NOT NULL,
    dir_general_apertura boolean NOT NULL,
    dir_general_cierre boolean NOT NULL,
    dir_general_reapertura boolean NOT NULL,
    dir_comercial_email character varying(254) NOT NULL,
    dir_comercial_apertura boolean NOT NULL,
    dir_comercial_cierre boolean NOT NULL,
    dir_comercial_reapertura boolean NOT NULL,
    dpt_calidad_email character varying(254) NOT NULL,
    dpt_calidad_apertura boolean NOT NULL,
    dpt_calidad_cierre boolean NOT NULL,
    dpt_calidad_reapertura boolean NOT NULL,
    comercial_apertura boolean NOT NULL,
    comercial_cierre boolean NOT NULL,
    comercial_reapertura boolean NOT NULL,
    otros_email character varying(254) NOT NULL,
    otros_apertura boolean NOT NULL,
    otros_cierre boolean NOT NULL,
    otros_reapertura boolean NOT NULL,
    tamano_maximo_adjunto integer,
    tamano_maximo_adjuntos integer,
    cierre_requiere_control boolean NOT NULL,
    logotipo bytea,
    fecha_licencia text NOT NULL,
    CONSTRAINT core_configuracion_tamano_maximo_adjunto_check CHECK ((tamano_maximo_adjunto >= 0)),
    CONSTRAINT core_configuracion_tamano_maximo_adjuntos_check CHECK ((tamano_maximo_adjuntos >= 0))
);


ALTER TABLE public.core_configuracion OWNER TO neondb_owner;

--
-- Name: core_configuracion_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_configuracion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_configuracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_detalle; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_detalle (
    id bigint NOT NULL,
    descripcion character varying(40) NOT NULL,
    tipo character varying(10) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    fecha_control timestamp with time zone,
    adjunto character varying(255) NOT NULL,
    notas text NOT NULL,
    control boolean NOT NULL,
    usuario_id integer NOT NULL,
    usuario_control_id integer,
    incidencia_id bigint NOT NULL
);


ALTER TABLE public.core_detalle OWNER TO neondb_owner;

--
-- Name: core_detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_detalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_incidencia; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_incidencia (
    id bigint NOT NULL,
    codigo character varying(20) NOT NULL,
    descripcion character varying(40) NOT NULL,
    notas text NOT NULL,
    fecha_apertura timestamp with time zone NOT NULL,
    fecha_ultimo timestamp with time zone NOT NULL,
    fecha_cierre timestamp with time zone,
    fecha_control timestamp with time zone,
    cerrado boolean NOT NULL,
    control boolean NOT NULL,
    calidad_id bigint NOT NULL,
    categoria_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    usuario_actualizacion_id integer NOT NULL,
    usuario_apertura_id integer NOT NULL,
    usuario_cierre_id integer,
    usuario_control_id integer
);


ALTER TABLE public.core_incidencia OWNER TO neondb_owner;

--
-- Name: core_incidencia_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_incidencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_incidencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_perfilusuario; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_perfilusuario (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    sistema boolean NOT NULL,
    modo character varying(10) NOT NULL,
    notas text NOT NULL,
    password_change boolean NOT NULL,
    activo boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_perfilusuario OWNER TO neondb_owner;

--
-- Name: core_perfilusuario_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_perfilusuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_perfilusuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_representante; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.core_representante (
    id bigint NOT NULL,
    codigo character varying(10) NOT NULL,
    descripcion character varying(40) NOT NULL,
    comercial_id bigint NOT NULL
);


ALTER TABLE public.core_representante OWNER TO neondb_owner;

--
-- Name: core_representante_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.core_representante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_representante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO neondb_owner;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO neondb_owner;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO neondb_owner;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO neondb_owner;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Acción	7	add_accion
26	Can change Acción	7	change_accion
27	Can delete Acción	7	delete_accion
28	Can view Acción	7	view_accion
29	Can add Calidad	8	add_calidad
30	Can change Calidad	8	change_calidad
31	Can delete Calidad	8	delete_calidad
32	Can view Calidad	8	view_calidad
33	Can add Categoría	9	add_categoria
34	Can change Categoría	9	change_categoria
35	Can delete Categoría	9	delete_categoria
36	Can view Categoría	9	view_categoria
37	Can add Cliente	10	add_cliente
38	Can change Cliente	10	change_cliente
39	Can delete Cliente	10	delete_cliente
40	Can view Cliente	10	view_cliente
41	Can add Comercial	11	add_comercial
42	Can change Comercial	11	change_comercial
43	Can delete Comercial	11	delete_comercial
44	Can view Comercial	11	view_comercial
45	Can add Configuración	12	add_configuracion
46	Can change Configuración	12	change_configuracion
47	Can delete Configuración	12	delete_configuracion
48	Can view Configuración	12	view_configuracion
49	Can add Incidencia	14	add_incidencia
50	Can change Incidencia	14	change_incidencia
51	Can delete Incidencia	14	delete_incidencia
52	Can view Incidencia	14	view_incidencia
53	Can add Detalle	13	add_detalle
54	Can change Detalle	13	change_detalle
55	Can delete Detalle	13	delete_detalle
56	Can view Detalle	13	view_detalle
57	Can add Perfil de usuario	15	add_perfilusuario
58	Can change Perfil de usuario	15	change_perfilusuario
59	Can delete Perfil de usuario	15	delete_perfilusuario
60	Can view Perfil de usuario	15	view_perfilusuario
61	Can add Representante	16	add_representante
62	Can change Representante	16	change_representante
63	Can delete Representante	16	delete_representante
64	Can view Representante	16	view_representante
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$3mtbhl0eBeyW4cZ3BbNdMA$JtYQAUzwxD7j9Mm7MBR+oRqrQu7MMdTKHjr3iyoP4e4=	2026-04-26 21:12:33.068289+00	t	CARLOS_RENDER			carlos.arca.barca.1970@gmail.com	t	t	2026-04-26 07:00:15.429928+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_accion; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_accion (id, codigo, descripcion, es_sistema, genera_detalle, detalle_tipo, detalle_descripcion, detalle_notas, enviar_email, email_to, email_cc, email_bcc, email_subject, email_body, email_attachments, email_editable) FROM stdin;
\.


--
-- Data for Name: core_calidad; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_calidad (id, codigo, descripcion, notas) FROM stdin;
1	Cal_001	Calidad varios	Problemas generales de calidad
2	Cal_002	Transporte	Problemas de transporte
3	Cal_003	Logistica	Problemas de logistica
4	Cal_004	Distribución	Problemas de distribucion
5	Cal_005	Roturas	Problemas con roturas
6	Cal_006	Calidad Seis	Problemas de calidad seis
\.


--
-- Data for Name: core_categoria; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_categoria (id, codigo, descripcion, notas) FROM stdin;
\.


--
-- Data for Name: core_cliente; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_cliente (id, codigo, descripcion, representante_id) FROM stdin;
\.


--
-- Data for Name: core_comercial; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_comercial (id, codigo, descripcion, email, telefono) FROM stdin;
\.


--
-- Data for Name: core_configuracion; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_configuracion (id, nombre_empresa, dir_general_email, dir_general_apertura, dir_general_cierre, dir_general_reapertura, dir_comercial_email, dir_comercial_apertura, dir_comercial_cierre, dir_comercial_reapertura, dpt_calidad_email, dpt_calidad_apertura, dpt_calidad_cierre, dpt_calidad_reapertura, comercial_apertura, comercial_cierre, comercial_reapertura, otros_email, otros_apertura, otros_cierre, otros_reapertura, tamano_maximo_adjunto, tamano_maximo_adjuntos, cierre_requiere_control, logotipo, fecha_licencia) FROM stdin;
\.


--
-- Data for Name: core_detalle; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_detalle (id, descripcion, tipo, fecha, fecha_control, adjunto, notas, control, usuario_id, usuario_control_id, incidencia_id) FROM stdin;
\.


--
-- Data for Name: core_incidencia; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_incidencia (id, codigo, descripcion, notas, fecha_apertura, fecha_ultimo, fecha_cierre, fecha_control, cerrado, control, calidad_id, categoria_id, cliente_id, usuario_actualizacion_id, usuario_apertura_id, usuario_cierre_id, usuario_control_id) FROM stdin;
\.


--
-- Data for Name: core_perfilusuario; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_perfilusuario (id, codigo, descripcion, sistema, modo, notas, password_change, activo, user_id) FROM stdin;
\.


--
-- Data for Name: core_representante; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.core_representante (id, codigo, descripcion, comercial_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-26 07:02:04.269783+00	1	Cal_001 - Calidad varios	1	[{"added": {}}]	8	1
2	2026-04-26 07:02:32.176609+00	2	Cal_002 - Transporte	1	[{"added": {}}]	8	1
3	2026-04-26 07:02:45.066364+00	3	Cal_003 - Logistica	1	[{"added": {}}]	8	1
4	2026-04-26 19:55:32.987587+00	4	Cal_004 - Distribución	1	[{"added": {}}]	8	1
5	2026-04-26 20:16:24.064962+00	5	Cal_005 - Roturas	1	[{"added": {}}]	8	1
6	2026-04-26 21:12:59.713052+00	6	Cal_006 - Calidad Seis	1	[{"added": {}}]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	accion
8	core	calidad
9	core	categoria
10	core	cliente
11	core	comercial
12	core	configuracion
13	core	detalle
14	core	incidencia
15	core	perfilusuario
16	core	representante
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-26 06:47:28.904614+00
2	auth	0001_initial	2026-04-26 06:47:32.849389+00
3	admin	0001_initial	2026-04-26 06:47:33.897145+00
4	admin	0002_logentry_remove_auto_add	2026-04-26 06:47:34.03131+00
5	admin	0003_logentry_add_action_flag_choices	2026-04-26 06:47:34.421254+00
6	contenttypes	0002_remove_content_type_name	2026-04-26 06:47:35.207424+00
7	auth	0002_alter_permission_name_max_length	2026-04-26 06:47:35.726135+00
8	auth	0003_alter_user_email_max_length	2026-04-26 06:47:36.244548+00
9	auth	0004_alter_user_username_opts	2026-04-26 06:47:36.507395+00
10	auth	0005_alter_user_last_login_null	2026-04-26 06:47:37.156006+00
11	auth	0006_require_contenttypes_0002	2026-04-26 06:47:37.413911+00
12	auth	0007_alter_validators_add_error_messages	2026-04-26 06:47:37.806051+00
13	auth	0008_alter_user_username_max_length	2026-04-26 06:47:38.461548+00
14	auth	0009_alter_user_last_name_max_length	2026-04-26 06:47:38.980385+00
15	auth	0010_alter_group_name_max_length	2026-04-26 06:47:39.502835+00
16	auth	0011_update_proxy_permissions	2026-04-26 06:47:39.765544+00
17	auth	0012_alter_user_first_name_max_length	2026-04-26 06:47:40.473403+00
18	core	0001_initial	2026-04-26 06:47:46.702995+00
19	core	0002_detalle_core_detall_inciden_b5c05e_idx_and_more	2026-04-26 06:47:47.656909+00
20	sessions	0001_initial	2026-04-26 06:47:48.56867+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_accion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_accion_id_seq', 1, false);


--
-- Name: core_calidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_calidad_id_seq', 6, true);


--
-- Name: core_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_categoria_id_seq', 1, false);


--
-- Name: core_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_cliente_id_seq', 1, false);


--
-- Name: core_comercial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_comercial_id_seq', 1, false);


--
-- Name: core_configuracion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_configuracion_id_seq', 1, false);


--
-- Name: core_detalle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_detalle_id_seq', 1, false);


--
-- Name: core_incidencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_incidencia_id_seq', 1, false);


--
-- Name: core_perfilusuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_perfilusuario_id_seq', 1, false);


--
-- Name: core_representante_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.core_representante_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 6, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_accion core_accion_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_accion
    ADD CONSTRAINT core_accion_codigo_key UNIQUE (codigo);


--
-- Name: core_accion core_accion_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_accion
    ADD CONSTRAINT core_accion_pkey PRIMARY KEY (id);


--
-- Name: core_calidad core_calidad_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_calidad
    ADD CONSTRAINT core_calidad_codigo_key UNIQUE (codigo);


--
-- Name: core_calidad core_calidad_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_calidad
    ADD CONSTRAINT core_calidad_pkey PRIMARY KEY (id);


--
-- Name: core_categoria core_categoria_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_categoria
    ADD CONSTRAINT core_categoria_codigo_key UNIQUE (codigo);


--
-- Name: core_categoria core_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_categoria
    ADD CONSTRAINT core_categoria_pkey PRIMARY KEY (id);


--
-- Name: core_cliente core_cliente_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_cliente
    ADD CONSTRAINT core_cliente_codigo_key UNIQUE (codigo);


--
-- Name: core_cliente core_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_cliente
    ADD CONSTRAINT core_cliente_pkey PRIMARY KEY (id);


--
-- Name: core_comercial core_comercial_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_comercial
    ADD CONSTRAINT core_comercial_codigo_key UNIQUE (codigo);


--
-- Name: core_comercial core_comercial_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_comercial
    ADD CONSTRAINT core_comercial_pkey PRIMARY KEY (id);


--
-- Name: core_configuracion core_configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_configuracion
    ADD CONSTRAINT core_configuracion_pkey PRIMARY KEY (id);


--
-- Name: core_detalle core_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_detalle
    ADD CONSTRAINT core_detalle_pkey PRIMARY KEY (id);


--
-- Name: core_incidencia core_incidencia_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_codigo_key UNIQUE (codigo);


--
-- Name: core_incidencia core_incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_pkey PRIMARY KEY (id);


--
-- Name: core_perfilusuario core_perfilusuario_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_perfilusuario
    ADD CONSTRAINT core_perfilusuario_codigo_key UNIQUE (codigo);


--
-- Name: core_perfilusuario core_perfilusuario_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_perfilusuario
    ADD CONSTRAINT core_perfilusuario_pkey PRIMARY KEY (id);


--
-- Name: core_perfilusuario core_perfilusuario_user_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_perfilusuario
    ADD CONSTRAINT core_perfilusuario_user_id_key UNIQUE (user_id);


--
-- Name: core_representante core_representante_codigo_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_representante
    ADD CONSTRAINT core_representante_codigo_key UNIQUE (codigo);


--
-- Name: core_representante core_representante_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_representante
    ADD CONSTRAINT core_representante_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_accion_codigo_eed8aeb6_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_accion_codigo_eed8aeb6_like ON public.core_accion USING btree (codigo varchar_pattern_ops);


--
-- Name: core_calidad_codigo_67baab06_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_calidad_codigo_67baab06_like ON public.core_calidad USING btree (codigo varchar_pattern_ops);


--
-- Name: core_categoria_codigo_94297c6a_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_categoria_codigo_94297c6a_like ON public.core_categoria USING btree (codigo varchar_pattern_ops);


--
-- Name: core_cliente_codigo_e1fa8f06_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_cliente_codigo_e1fa8f06_like ON public.core_cliente USING btree (codigo varchar_pattern_ops);


--
-- Name: core_cliente_representante_id_cc3c84b2; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_cliente_representante_id_cc3c84b2 ON public.core_cliente USING btree (representante_id);


--
-- Name: core_comercial_codigo_a64d03ea_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_comercial_codigo_a64d03ea_like ON public.core_comercial USING btree (codigo varchar_pattern_ops);


--
-- Name: core_detall_fecha_115604_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_detall_fecha_115604_idx ON public.core_detalle USING btree (fecha);


--
-- Name: core_detall_inciden_b5c05e_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_detall_inciden_b5c05e_idx ON public.core_detalle USING btree (incidencia_id);


--
-- Name: core_detalle_incidencia_id_f3983722; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_detalle_incidencia_id_f3983722 ON public.core_detalle USING btree (incidencia_id);


--
-- Name: core_detalle_usuario_control_id_882b0871; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_detalle_usuario_control_id_882b0871 ON public.core_detalle USING btree (usuario_control_id);


--
-- Name: core_detalle_usuario_id_8f66517e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_detalle_usuario_id_8f66517e ON public.core_detalle USING btree (usuario_id);


--
-- Name: core_incide_cerrado_edbaba_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incide_cerrado_edbaba_idx ON public.core_incidencia USING btree (cerrado);


--
-- Name: core_incide_cliente_a08798_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incide_cliente_a08798_idx ON public.core_incidencia USING btree (cliente_id);


--
-- Name: core_incide_fecha_a_c95895_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incide_fecha_a_c95895_idx ON public.core_incidencia USING btree (fecha_apertura);


--
-- Name: core_incidencia_calidad_id_ecd30697; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_calidad_id_ecd30697 ON public.core_incidencia USING btree (calidad_id);


--
-- Name: core_incidencia_categoria_id_258a9364; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_categoria_id_258a9364 ON public.core_incidencia USING btree (categoria_id);


--
-- Name: core_incidencia_cliente_id_596d6fed; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_cliente_id_596d6fed ON public.core_incidencia USING btree (cliente_id);


--
-- Name: core_incidencia_codigo_763dad91_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_codigo_763dad91_like ON public.core_incidencia USING btree (codigo varchar_pattern_ops);


--
-- Name: core_incidencia_usuario_actualizacion_id_3b91ebbb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_usuario_actualizacion_id_3b91ebbb ON public.core_incidencia USING btree (usuario_actualizacion_id);


--
-- Name: core_incidencia_usuario_apertura_id_cb1e5241; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_usuario_apertura_id_cb1e5241 ON public.core_incidencia USING btree (usuario_apertura_id);


--
-- Name: core_incidencia_usuario_cierre_id_78553b13; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_usuario_cierre_id_78553b13 ON public.core_incidencia USING btree (usuario_cierre_id);


--
-- Name: core_incidencia_usuario_control_id_a678560d; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_incidencia_usuario_control_id_a678560d ON public.core_incidencia USING btree (usuario_control_id);


--
-- Name: core_perfilusuario_codigo_1f6fa275_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_perfilusuario_codigo_1f6fa275_like ON public.core_perfilusuario USING btree (codigo varchar_pattern_ops);


--
-- Name: core_representante_codigo_a500515c_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_representante_codigo_a500515c_like ON public.core_representante USING btree (codigo varchar_pattern_ops);


--
-- Name: core_representante_comercial_id_b87583b9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX core_representante_comercial_id_b87583b9 ON public.core_representante USING btree (comercial_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cliente core_cliente_representante_id_cc3c84b2_fk_core_representante_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_cliente
    ADD CONSTRAINT core_cliente_representante_id_cc3c84b2_fk_core_representante_id FOREIGN KEY (representante_id) REFERENCES public.core_representante(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_detalle core_detalle_incidencia_id_f3983722_fk_core_incidencia_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_detalle
    ADD CONSTRAINT core_detalle_incidencia_id_f3983722_fk_core_incidencia_id FOREIGN KEY (incidencia_id) REFERENCES public.core_incidencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_detalle core_detalle_usuario_control_id_882b0871_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_detalle
    ADD CONSTRAINT core_detalle_usuario_control_id_882b0871_fk_auth_user_id FOREIGN KEY (usuario_control_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_detalle core_detalle_usuario_id_8f66517e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_detalle
    ADD CONSTRAINT core_detalle_usuario_id_8f66517e_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_calidad_id_ecd30697_fk_core_calidad_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_calidad_id_ecd30697_fk_core_calidad_id FOREIGN KEY (calidad_id) REFERENCES public.core_calidad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_categoria_id_258a9364_fk_core_categoria_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_categoria_id_258a9364_fk_core_categoria_id FOREIGN KEY (categoria_id) REFERENCES public.core_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_cliente_id_596d6fed_fk_core_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_cliente_id_596d6fed_fk_core_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.core_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_usuario_actualizacio_3b91ebbb_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_usuario_actualizacio_3b91ebbb_fk_auth_user FOREIGN KEY (usuario_actualizacion_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_usuario_apertura_id_cb1e5241_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_usuario_apertura_id_cb1e5241_fk_auth_user_id FOREIGN KEY (usuario_apertura_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_usuario_cierre_id_78553b13_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_usuario_cierre_id_78553b13_fk_auth_user_id FOREIGN KEY (usuario_cierre_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incidencia core_incidencia_usuario_control_id_a678560d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_incidencia
    ADD CONSTRAINT core_incidencia_usuario_control_id_a678560d_fk_auth_user_id FOREIGN KEY (usuario_control_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_perfilusuario core_perfilusuario_user_id_f33b9be3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_perfilusuario
    ADD CONSTRAINT core_perfilusuario_user_id_f33b9be3_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_representante core_representante_comercial_id_b87583b9_fk_core_comercial_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.core_representante
    ADD CONSTRAINT core_representante_comercial_id_b87583b9_fk_core_comercial_id FOREIGN KEY (comercial_id) REFERENCES public.core_comercial(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

\unrestrict eDQTXbxkuUIEgGuqwWZD69CCsy5O8eyo9FK3gWvNTmdTLFcHgaAUlnDr0XdRdD1

