# Generated by Django 6.0.4 on 2026-04-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es sistema')),
                ('genera_detalle', models.BooleanField(default=False, verbose_name='Genera detalle')),
                ('detalle_tipo', models.CharField(blank=True, max_length=10, verbose_name='Tipo de detalle')),
                ('detalle_descripcion', models.CharField(blank=True, max_length=40, verbose_name='Descripción del detalle')),
                ('detalle_notas', models.TextField(blank=True, verbose_name='Notas del detalle')),
                ('enviar_email', models.BooleanField(default=False, verbose_name='Enviar email')),
                ('email_to', models.EmailField(blank=True, max_length=254, verbose_name='Destinatario')),
                ('email_cc', models.TextField(blank=True, verbose_name='CC')),
                ('email_bcc', models.TextField(blank=True, verbose_name='BCC')),
                ('email_subject', models.CharField(blank=True, max_length=254, verbose_name='Asunto')),
                ('email_body', models.TextField(blank=True, verbose_name='Cuerpo del email')),
                ('email_attachments', models.BooleanField(default=False, verbose_name='Adjuntos email')),
                ('email_editable', models.BooleanField(default=False, verbose_name='Email editable')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Calidad',
                'verbose_name_plural': 'Calidades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Comercial',
                'verbose_name_plural': 'Comerciales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=40, verbose_name='Nombre empresa')),
                ('dir_general_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Dirección General')),
                ('dir_general_apertura', models.BooleanField(default=False, verbose_name='DG - Apertura')),
                ('dir_general_cierre', models.BooleanField(default=False, verbose_name='DG - Cierre')),
                ('dir_general_reapertura', models.BooleanField(default=False, verbose_name='DG - Reapertura')),
                ('dir_comercial_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Dirección Comercial')),
                ('dir_comercial_apertura', models.BooleanField(default=False, verbose_name='DC - Apertura')),
                ('dir_comercial_cierre', models.BooleanField(default=False, verbose_name='DC - Cierre')),
                ('dir_comercial_reapertura', models.BooleanField(default=False, verbose_name='DC - Reapertura')),
                ('dpt_calidad_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Calidad')),
                ('dpt_calidad_apertura', models.BooleanField(default=False, verbose_name='Calidad - Apertura')),
                ('dpt_calidad_cierre', models.BooleanField(default=False, verbose_name='Calidad - Cierre')),
                ('dpt_calidad_reapertura', models.BooleanField(default=False, verbose_name='Calidad - Reapertura')),
                ('comercial_apertura', models.BooleanField(default=False, verbose_name='Comercial - Apertura')),
                ('comercial_cierre', models.BooleanField(default=False, verbose_name='Comercial - Cierre')),
                ('comercial_reapertura', models.BooleanField(default=False, verbose_name='Comercial - Reapertura')),
                ('otros_email', models.EmailField(blank=True, max_length=254, verbose_name='Otros emails')),
                ('otros_apertura', models.BooleanField(default=False, verbose_name='Otros - Apertura')),
                ('otros_cierre', models.BooleanField(default=False, verbose_name='Otros - Cierre')),
                ('otros_reapertura', models.BooleanField(default=False, verbose_name='Otros - Reapertura')),
                ('tamano_maximo_adjunto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño máximo adjunto')),
                ('tamano_maximo_adjuntos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño máximo adjuntos')),
                ('cierre_requiere_control', models.BooleanField(default=False, verbose_name='Cierre requiere control')),
                ('logotipo', models.BinaryField(blank=True, null=True, verbose_name='Logotipo')),
                ('fecha_licencia', models.TextField(blank=True, verbose_name='Fecha licencia')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha apertura')),
                ('fecha_ultimo', models.DateTimeField(verbose_name='Última actualización')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('fecha_control', models.DateTimeField(blank=True, null=True, verbose_name='Fecha control')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('control', models.BooleanField(default=False, verbose_name='Control')),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='core.calidad', verbose_name='Calidad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='core.categoria', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='core.cliente', verbose_name='Cliente')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario última actualización')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_abiertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario apertura')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cierre')),
                ('usuario_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_controladas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario control')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('fecha_control', models.DateTimeField(blank=True, null=True, verbose_name='Fecha control')),
                ('adjunto', models.CharField(blank=True, max_length=255, verbose_name='Adjunto')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('control', models.BooleanField(default=False, verbose_name='Control')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_controlados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario control')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.incidencia', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('sistema', models.BooleanField(default=False, verbose_name='Usuario de sistema')),
                ('modo', models.CharField(blank=True, max_length=10, verbose_name='Modo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('password_change', models.BooleanField(default=False, verbose_name='Debe cambiar contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representantes', to='core.comercial', verbose_name='Comercial')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.representante', verbose_name='Representante'),
        ),
    ]
