# Generated by Django 6.0.4 on 2026-04-22 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalle',
            index=models.Index(fields=['incidencia'], name='core_detall_inciden_b5c05e_idx'),
        ),
        migrations.AddIndex(
            model_name='detalle',
            index=models.Index(fields=['fecha'], name='core_detall_fecha_115604_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['cliente'], name='core_incide_cliente_a08798_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_apertura'], name='core_incide_fecha_a_c95895_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['cerrado'], name='core_incide_cerrado_edbaba_idx'),
        ),
    ]
