# Generated by Django 6.0.4 on 2026-05-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalle_core_detall_inciden_b5c05e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='codigo',
        ),
    ]
