# Generated by Django 6.0.4 on 2026-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_incidencia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='detalle_descripcion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripción del detalle'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='detalle_tipo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de detalle'),
        ),
    ]
