# Generated by Django 6.0.4 on 2026-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accion_detalle_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='email_bcc',
            field=models.EmailField(blank=True, max_length=254, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='email_cc',
            field=models.EmailField(blank=True, max_length=254, verbose_name='CC'),
        ),
    ]
